name: chat_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_messaging: ^14.3.0
  cloud_firestore: ^4.4.5
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  get_cli: ^1.8.1
  google_sign_in: ^6.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_local_notifications: ^13.0.0
  firebase_storage: ^11.0.16

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Roxborough CF
      fonts:
        - asset: assets/fonts/roxborough-cf-thin.ttf

